server:
  port: 8080

spring:
  main:
    banner-mode: off
  application:
    name: acreditacion-backend

logging:
  level:
    org.springframework: WARN
    com.undec.acreditacion: INFO
    org.flywaydb: INFO
